# Generated by Django 4.2.7 on 2023-11-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=20)),
                ('doctors_name', models.CharField(max_length=225)),
                ('time_slot', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('appointment_date', models.CharField(max_length=22)),
                ('token_number', models.CharField(max_length=225)),
                ('problem', models.TextField(max_length=225)),
            ],
        ),
    ]
