# Generated by Django 4.2.7 on 2023-11-29 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='patient_id',
            new_name='patient_name',
        ),
    ]
