# Generated by Django 4.2.7 on 2023-11-29 01:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_rename_patient_id_appointments_patient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='special_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
