# Generated by Django 4.2.7 on 2023-11-29 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointments_special_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='special_id',
            field=models.CharField(default='f5bfd8e3ad6b412994a6fe5c3416716e', editable=False, max_length=32, unique=True),
        ),
    ]
