# Generated by Django 4.2.7 on 2023-11-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_appointments_special_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='special_id',
            field=models.CharField(default='83cf3', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='token_number',
            field=models.CharField(default='49eb15', editable=False, max_length=32, unique=True),
        ),
    ]
