# Generated by Django 4.2.7 on 2023-11-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_alter_appointments_special_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='special_id',
            field=models.CharField(default='22dec', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='token_number',
            field=models.CharField(max_length=32),
        ),
    ]
