# Generated by Django 4.2.7 on 2023-11-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_patients',
            name='confirm',
        ),
        migrations.AlterField(
            model_name='add_patients',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
