# Generated by Django 4.2.7 on 2023-11-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('specialization', models.CharField(max_length=225)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('details', models.TextField(max_length=225)),
                ('date_of_birth', models.DateField()),
                ('experience', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=225)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
