# Generated by Django 4.2.7 on 2023-11-28 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointments',
        ),
    ]
